name: .NET and ZAP Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-hello:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Test HelloService
      run: |
        cd hello-service/HelloService
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal

  build-and-test-world:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Test WorldService
      run: |
        cd world-service/WorldService
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal

  zap-testing-hello:

    runs-on: ubuntu-latest

    needs: build-and-test-hello

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OWASP ZAP
      uses: zaproxy/action-baseline@v2
      with:
        target: "http://hello-service-hello-service-url"  # Replace with the actual URL of HelloService

    - name: Run OWASP ZAP
      uses: zaproxy/action-baseline@v2
      with:
        zap-host: "localhost"  # Change if ZAP is running on a different host
        zap-port: "8080"       # Change if ZAP is running on a different port

  zap-testing-world:

    runs-on: ubuntu-latest

    needs: build-and-test-world

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OWASP ZAP
      uses: zaproxy/action-baseline@v2
      with:
        target: "http://world-service-world-service-url"  # Replace with the actual URL of WorldService

    - name: Run OWASP ZAP
      uses: zaproxy/action-baseline@v2
      with:
        zap-host: "localhost"  # Change if ZAP is running on a different host
        zap-port: "8080"       # Change if ZAP is running on a different port
