name: .NET and ZAP Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

  build-and-test-hello:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies and Build HelloService
      run: |
        cd hello-service/HelloService
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal

  zap-testing-hello:
    runs-on: ubuntu-latest
    needs: build-and-test-hello
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OWASP ZAP
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: "http://hello-service-hello-service-url"  # Replace with the actual URL of HelloService

    - name: Run OWASP ZAP
      uses: zaproxy/action-baseline@v0.11.0
      with:
        zap-host: "localhost"  # Change if ZAP is running on a different host
        zap-port: "8080"       # Change if ZAP is running on a different port
